import './globals.css'
import { Space_Mono} from 'next/font/google'

const mono = Space_Mono({ subsets: ['latin'],weight:['700','400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mono.className}>{children}</body>
    </html>
  )
}
